"""Computed capital/risk allocation and simulated net-wealth teaching figures."""
import json
from pathlib import Path
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import course_pages, execute_chapter

ROOT = Path(__file__).resolve().parents[1]


def save(chart,name,description):
    chart.save(name,description)
    suffix='-mobile' if chart.w==400 else ''
    path=ROOT/f'assets/charts/{name}{suffix}.svg'
    path.write_text(path.read_text().replace('Generated by scripts/make_course_figures.py.',
                                            'Generated by scripts/make_risk_budget_figures.py.'))


def main():
    pages={p['file']:p for p in course_pages('advanced',4)}
    _,risk,_=execute_chapter(pages['risk-contributions'])
    _,backtest,_=execute_chapter(pages['diversification-backtest'])
    capital=risk['weights']*100
    shares=risk['components']['Risk share'].to_numpy()*100
    wealth=backtest['net_wealth']
    assert wealth.min().min()>=.8 and wealth.max().max()<=2.1
    methods=['EW','IV','GMV','ERC','MaxDR']
    colors=[GRAY,'#b45f06',TEAL,PURPLE,'#1565c0']
    dashes=['6 5','2 3','','','8 3 2 3']
    for width in (720,400):
        chart=Chart(width,'เงินลงทุนกับส่วนแบ่งความเสี่ยง','สี่สินทรัพย์สมมติ · Covariance คงที่',
                    (.5,4.5),(0,80),[],[0,20,40,60,80],'สินทรัพย์','สัดส่วน (%)')
        chart.legend(90,'น้ำหนักเงินลงทุน',PURPLE)
        chart.legend(116,'ส่วนแบ่งความเสี่ยง',TEAL)
        bar_width=20 if width==400 else 36
        for i,asset in enumerate(risk['assets'],1):
            chart.text(chart.x(i),chart.bottom+25,asset,16,anchor='middle')
            for offset,value,color,name in ((-bar_width,capital[i-1],PURPLE,'capital-weight'),
                                             (2,shares[i-1],TEAL,'relative-risk')):
                chart.parts.append(f'<rect data-series="{name}" data-asset="{asset}" x="{chart.x(i)+offset:.4f}" y="{chart.y(value):.4f}" width="{bar_width-2}" height="{chart.bottom-chart.y(value):.4f}" fill="{color}"/>')
        save(chart,'advanced-capital-risk','Original four-asset annual covariance fixture. Purple bars are capital weights 50/20/20/10 percent. Teal bars are relative Euler risk contributions w_i*(Sigma*w)_i/(w*Sigma*w). Each set sums to 100%, but these are different allocations. Portfolio annual volatility is approximately 14.0872%; the relative contributions themselves are not asset volatilities or probabilities.')
        chart=Chart(width,'เปรียบเทียบพอร์ตหลังหักต้นทุน','ข้อมูลจำลอง · ค่าซื้อหรือขาย 10 bps',
                    (36,96),(.8,2.1),[36,48,60,72,84,96],[.8,1.0,1.2,1.4,1.6,1.8,2.0],
                    'เดือนจำลอง (36 = ก่อนลงทุน)','มูลค่าพอร์ต (เริ่มต้น 1)')
        for i,(method,color,dash) in enumerate(zip(methods,colors,dashes)):
            x=22 if i%2==0 else (210 if width==400 else 320)
            y=88+(i//2)*24
            chart.line(x,y-5,x+26,y-5,color,3,dash)
            chart.text(x+36,y,method,15 if width==400 else 18)
            chart.series(wealth.index,wealth[method],color,method,dash)
        save(chart,'advanced-diversification-net-wealth','Original bounded IID simulation, seed 20261004, four assets, 96 monthly observations and a 36-month rolling training window. All methods use only preceding data and share long-only fully-invested constraints. All wealth paths begin at 1 before month 37 and deduct a 10-basis-point cost per unit bought or sold, including initial investment. No terminal liquidation. Lines connect simulated monthly observations; this single path does not establish a universal strategy ranking.')
    data={'status':'Original hypothetical fixture and bounded IID simulation',
          'capital_risk':{'assets':risk['assets'],'capital_weight_percent':capital.tolist(),
                          'relative_risk_percent':shares.tolist(),'annual_portfolio_variance':float(risk['portfolio_variance'])},
          'net_wealth':{'month':wealth.index.tolist(),'cost_bps':10,'methods':{name:wealth[name].tolist() for name in methods}}}
    (ROOT/'data/advanced-risk-budget-figures.json').write_text(json.dumps(data,indent=2)+'\n')
    print('Generated 4 Advanced Module 4 responsive SVGs')


if __name__=='__main__':
    main()
