"""Computed ML coefficient paths and genuine sequential probability forecasts."""
import json
from pathlib import Path
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import execute_chapter

ROOT=Path(__file__).resolve().parents[1]

def save(chart,name,description):
    chart.save(name,description)
    suffix='-mobile' if chart.w==400 else ''
    file=ROOT/f'assets/charts/{name}{suffix}.svg'
    file.write_text(file.read_text().replace('Generated by scripts/make_course_figures.py.',
                                            'Generated by scripts/make_ml_figures.py.'))


def main():
    _,regularized,_=execute_chapter({'file':'regularized-factor-models'})
    _,prediction,_=execute_chapter({'file':'recession-models'})
    _,validation,_=execute_chapter({'file':'model-validation'})
    _,portfolio,_=execute_chapter({'file':'ml-portfolio-lab'})
    _,regimes,_=execute_chapter({'file':'market-regimes'})
    output={'status':'Original hypothetical fixtures and seeded simulation; no observed market forecasts',
            'factor_paths':{},'event_forecast':prediction['forecast'].to_dict(orient='list')}
    output['event_forecast']['actual']=prediction['actual'].tolist()
    for method,name,xticks in [('Ridge','ridge_path',[0,1,3,6,9]),('Lasso','lasso_path',[0,.01,.02,.03])]:
        path=regularized[name]
        output['factor_paths'][method]=path.to_dict(orient='list')
        for width in (720,400):
            chart=Chart(width,method+' coefficient path',
                        'ตัวอย่างสมมติ · แปดแถว · สามปัจจัย',
                        (0,float(path['lambda'].max())),(-.08,2.1),xticks,[0,.5,1,1.5,2],
                        'Penalty λ (convention ตามบทเรียน)','Coefficient (จุดเปอร์เซ็นต์/เดือน)')
            for j,(factor,color,dash) in enumerate([('F1',PURPLE,''),('F2',TEAL,'6 4'),('F3',GRAY,'2 3')]):
                chart.legend(90+25*j,factor,color,dash)
                chart.series(path['lambda'],100*path[factor],color,factor,dash)
                for x,y in zip(path['lambda'],100*path[factor]): chart.dot(x,y,color,3)
            save(chart,'ml-factor-'+method.lower(),
                 f'{method} path on an original centered orthogonal 8-by-3 design with unit column population variance. '
                 'Target has intercept 0.002, coefficients [0.020,0.007,0] and an orthogonal residual of magnitude 0.001. '
                 'Coordinates are actual fitted coefficients times 100 (percentage points per month per standardized feature unit). '
                 'Ridge convention is SSE/(2n)+lambda*||beta||^2/2, implemented with sklearn alpha=n*lambda. '
                 'Lasso convention is SSE/(2n)+lambda*||beta||_1. Lambda axes are not interchangeable. Lines join evaluated grid values.')
    forecast=prediction['forecast']
    for width in (720,400):
        chart=Chart(width,'Probability กับเหตุการณ์จริง','ข้อมูลจำลอง · พยากรณ์เดือนถัดไป',
                    (180,238),(-.04,1.04),[180,190,200,210,220,230,238],[0,.25,.5,.75,1],
                    'เดือนที่ออกคำพยากรณ์ (origin)','Probability / Label (0 หรือ 1)')
        chart.legend(90,'Logistic probability',PURPLE)
        chart.legend(115,'อัตราในชุดฝึกที่พร้อมใช้',TEAL,'6 4')
        chart.text(22,142,'● ผลจริง 0 = ไม่เกิด, 1 = เกิด',15,color=GRAY)
        chart.series(forecast.origin,forecast.p,PURPLE,'probability')
        chart.series(forecast.origin,forecast.baseline,TEAL,'released-label-baseline','6 4')
        for x,y in zip(forecast.origin,prediction['actual']): chart.dot(x,y,GRAY,3)
        save(chart,'ml-event-probabilities',
             'Original 240-month simulation, seed 501. Features have explicitly modelled release times. '
             'Each origin t forecasts the event at t+1; a training label is usable only from its origin+3. '
             'Logistic settings were selected from chronological validation completed by origin 180 and frozen. '
             'Coefficients refit on newly available historical labels each month. 59 forecasts cover origins 180-238; '
             '14 positive target labels are displayed as gray points at 1, remaining 45 at 0. '
             'Purple is predicted probability, teal is historical frequency in the released training labels. '
             'No real macroeconomic data or recession probability is shown.')
    output['knn_validation']=validation['knn_selection'].to_dict(orient='list')
    wealth=portfolio['heldout_gross_wealth']
    output['portfolio_wealth']={'dates':[str(d.date()) for d in wealth.index],
                               'series':wealth.to_dict(orient='list')}
    output['tv_levels']={'observed':regimes['trend_y'].tolist(),
                         'fitted':regimes['trend_level'].tolist(), 'penalty':regimes['trend_penalty']}
    for width in (720,400):
        c=Chart(width,'KNN: ฝึกดีแล้วทดสอบดีด้วยไหม','ข้อมูลจำลอง · train 100, validation 40',
                (0,26),(-2,52),[1,5,9,15,25],[0,10,20,30,40,50],
                'จำนวนเพื่อนบ้าน K','อัตราทายผิด (%)')
        for y,name,color,dash in [(validation['knn_train_errors'],'Train',TEAL,'6 4'),
                                  (validation['knn_validation_errors'],'Validation',PURPLE,'')]:
            c.legend(90 if name=='Train' else 115,name,color,dash)
            c.series(validation['k_grid'],100*y,color,name.lower(),dash)
            for x,value in zip(validation['k_grid'],y):c.dot(x,100*value,color,3)
        c.text(22,145,'เลือก K = 9 จาก validation ก่อนเปิด test',14,color=GRAY)
        save(c,'ml-knn-validation','Original binary classification simulation, seed 20261003. '
             'K in [1,3,5,9,15,25]; 100 training and 40 validation observations. '
             'Scaler is fit on training rows. Plotted misclassification errors are calculated from actual fitted '
             'KNN models. K=9 minimizes validation error; the 40 final test observations are not plotted or used for this choice.')
        c=Chart(width,'พอร์ตในช่วงที่กันไว้','ข้อมูลจำลอง · ซื้อแล้วถือ · ยังไม่หักต้นทุน',
                (0,52),(.96,1.13),[0,13,26,39,52],[.96,1,1.04,1.08,1.12],
                'สัปดาห์หลังสิ้นสุดชุดฝึก','มูลค่า (เงินตั้งต้น = 1)')
        for j,(name,color,dash) in enumerate([('EW',PURPLE,''),('GMV',TEAL,''),
                                             ('MSR','#212121','7 3'),('Cash',GRAY,'2 3')]):
            c.legend(86+22*j,name,color,dash)
            c.series(np.arange(len(wealth)),wealth[name],color,name,dash)
        save(c,'ml-portfolio-heldout','Original 156-week three-asset simulation, seed 20261004. '
             'Weights estimated from first 104 rows only, then held without rebalancing over 52 test weeks. '
             'All 53 observations include initial wealth at 2021-12-24 and dates through 2022-12-23. '
             'GMV and MSR are long-only fully invested. Cash grows at a stipulated 0.0005 weekly rate. '
             'Gross wealth excludes transaction costs; no empirical strategy ranking is implied.')
        c=Chart(width,'ระดับผลตอบแทนเป็นช่วง','ตัวอย่างสมมติ · วิเคราะห์ย้อนหลัง 16 ปี',
                (1,16),(-12,10),[1,4,8,12,16],[-10,-5,0,5,10],
                'ปีในตัวอย่าง','ผลตอบแทน / ระดับที่ fit (%) ต่อปี')
        c.legend(90,'ผลตอบแทนสมมติ',GRAY,'3 3')
        c.legend(115,'TV level · λ = 0.06',PURPLE)
        c.text(22,145,'ใช้ข้อมูลทั้ง 16 ปี: ไม่ใช่ forecast',14,color=GRAY)
        years=np.arange(1,17)
        c.series(years,100*regimes['trend_y'],GRAY,'observed','3 3')
        for x,y in zip(years,regimes['trend_y']):c.dot(x,100*y,GRAY,3)
        # Midpoint steps keep fitted annual levels constant between observations.
        steps=np.repeat(np.arange(1.5,16),2)
        xs=np.r_[1,steps,16]
        ys=np.repeat(100*regimes['trend_level'],2)
        c.series(xs,ys,PURPLE,'fitted-level')
        save(c,'ml-tv-levels','Original authored 16-year annual return series. '
             'First-difference total-variation penalty minimizes 0.5*SSE+0.06*sum(abs(diff(level))). '
             'Fitted levels are 0.048 for years 1-5, -0.06 for years 6-10, 0.02 for years 11-16. '
             'Purple steps meet at midpoints between annual observations. '
             'This is retrospective full-sample smoothing, not an available-at-the-time investment signal.')
    (ROOT/'data/ml-figures.json').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n')
    print('Generated 12 responsive ML SVG figures from executed lesson namespaces')

if __name__=='__main__': main()
