"""Original deterministic charts for Advanced Module 1, using lesson fixtures."""
import json
from pathlib import Path
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import execute_chapter, course_pages

ROOT = Path(__file__).resolve().parents[1]

def save(chart, name, description):
    chart.save(name, description)
    suffix = '-mobile' if chart.w == 400 else ''
    path = ROOT / f'assets/charts/{name}{suffix}.svg'
    path.write_text(path.read_text().replace('Generated by scripts/make_course_figures.py.',
                                           'Generated by scripts/make_advanced_figures.py.'))


def main():
    page = next(p for p in course_pages('advanced', 1) if p['file'] == 'style-analysis')
    _, ns, _ = execute_chapter(page)
    weights = ns['style_rolling'].to_numpy()
    x = np.arange(12) * .01 - .05
    y = .001 + 1.2 * x + np.tile([1, -1, -1, 1], 3) * .004
    fit = np.linalg.lstsq(np.column_stack([np.ones(12), x]), y, rcond=None)[0]
    np.testing.assert_allclose(fit, [.001, 1.2], atol=1e-14)
    for width in (720, 400):
        c = Chart(width, 'Beta คือความชันของเส้น', 'ข้อมูลสมมติ 12 เดือน · alpha 0.1%/เดือน',
                  (-6, 7), (-7, 9), [-5, 0, 5], [-5, 0, 5],
                  'Market excess return (%/เดือน)', 'Fund excess return (%/เดือน)')
        c.legend(96, 'ค่าที่ประมาณจากเส้นตรง', PURPLE)
        c.legend(124, 'ผลตอบแทนกองทุนแต่ละเดือน', TEAL)
        c.series(x*100, (.001+1.2*x)*100, PURPLE, 'fitted-excess-return')
        for xx, yy in zip(x,y): c.dot(xx*100, yy*100, TEAL, 4)
        save(c, 'advanced-factor-fit', 'Original hypothetical monthly excess returns. Twelve points use market x=-0.05 to 0.06, fund=0.001+1.2*x plus authored residuals alternating in blocks [0.004,-0.004,-0.004,0.004]. Line shows fitted alpha and beta, not a forecast.')
        c = Chart(width, 'น้ำหนักที่ประมาณจาก 16 เดือนล่าสุด', 'ข้อมูลสมมติ · เปลี่ยนสไตล์หลังเดือน 16',
                  (16, 32), (0, 70), [16,20,24,28,32], [0,20,40,60],
                  'เดือนสุดท้ายที่ใช้ประมาณ', 'น้ำหนักใน benchmark (%)')
        for i,(label,col,dash) in enumerate([('Value',PURPLE,''),('Growth',TEAL,'6 5'),('Bonds',GRAY,'3 3')]):
            c.legend(88+i*24,label,col,dash)
            c.series(np.arange(16,33),weights[:,i]*100,col,label,dash)
        save(c, 'advanced-style-drift', 'Original hypothetical 32-month example. Each estimate uses only the 16 months ending at its x-axis date. Underlying mixture changes from 50/30/20 to 20/60/20 after month16. Line segments join monthly fitted values. This is retrospective style attribution, not future-return prediction.')
    (ROOT/'data/advanced-figures.json').write_text(json.dumps({
        'status':'original hypothetical teaching fixtures',
        'factor':{'market_excess':x.tolist(),'fund_excess':y.tolist(),'intercept':float(fit[0]),'beta':float(fit[1])},
        'style':{'month_end':list(range(16,33)),'columns':['Value','Growth','Bonds'],'rolling_weights':weights.tolist()}
    },indent=2)+'\n')
    print('Generated 4 Advanced Module 1 responsive SVGs')


if __name__ == '__main__': main()
