"""Deterministic teaching charts for Modules 2–4; all inputs are hypothetical."""
import base64
from html import escape
import json
from pathlib import Path
import numpy as np
from scipy.optimize import minimize

ROOT = Path(__file__).resolve().parents[1]
PURPLE, TEAL, GRAY = '#6200ee', '#00796e', '#616161'


class Chart:
    def __init__(self, width, title, subtitle, xlim, ylim, xticks, yticks, xlabel, ylabel):
        self.w, self.h = width, 540 if width == 400 else 560
        self.left, self.right, self.top, self.bottom = 60, width - 24, 185, self.h - 88
        self.xlim, self.ylim = xlim, ylim
        self.parts = [f'<rect width="{width}" height="{self.h}" fill="#fff"/>']
        self.text(20, 32, title, 20 if width == 400 else 26)
        self.text(20, 62, subtitle, 15 if width == 400 else 18, color=GRAY)
        self.text(self.left, self.top - 16, ylabel, 15)
        for tick in xticks:
            self.line(self.x(tick), self.top, self.x(tick), self.bottom, '#eeeeee', 1)
            self.text(self.x(tick), self.bottom + 25, f'{tick:g}', 15, anchor='middle')
        for tick in yticks:
            self.line(self.left, self.y(tick), self.right, self.y(tick), '#ddd', 1)
            self.text(self.left - 8, self.y(tick) + 5, f'{tick:g}', 15, anchor='end')
        self.text((self.left + self.right) / 2, self.h - 32, xlabel, 16, anchor='middle')

    def x(self, value):
        return self.left + (value - self.xlim[0]) / (self.xlim[1] - self.xlim[0]) * (self.right - self.left)

    def y(self, value):
        return self.bottom - (value - self.ylim[0]) / (self.ylim[1] - self.ylim[0]) * (self.bottom - self.top)

    def text(self, x, y, value, size=16, color='#212121', anchor='start'):
        self.parts.append(f'<text x="{x:.3f}" y="{y:.3f}" font-size="{size}" fill="{color}" text-anchor="{anchor}">{escape(str(value))}</text>')

    def line(self, x1, y1, x2, y2, color, width=2, dash=''):
        self.parts.append(f'<line x1="{x1:.3f}" y1="{y1:.3f}" x2="{x2:.3f}" y2="{y2:.3f}" stroke="{color}" stroke-width="{width}" stroke-dasharray="{dash}"/>')

    def legend(self, y, name, color, dash=''):
        self.line(22, y-5, 50, y-5, color, 3, dash)
        self.text(60, y, name, 15 if self.w == 400 else 18)

    def series(self, xs, ys, color, name, dash=''):
        points = ' '.join(f'{self.x(x):.4f},{self.y(y):.4f}' for x, y in zip(xs, ys))
        self.parts.append(f'<polyline data-series="{name}" points="{points}" stroke="{color}" stroke-width="3" stroke-dasharray="{dash}" fill="none"/>')

    def dot(self, x, y, color=GRAY, radius=3):
        self.parts.append(f'<circle cx="{self.x(x):.3f}" cy="{self.y(y):.3f}" r="{radius}" fill="{color}"/>')

    def save(self, name, description):
        fonts = ''
        for family, file in [('Roboto', 'roboto-latin-400-normal.woff2'), ('Noto Sans Thai', 'noto-sans-thai-thai-400-normal.woff2')]:
            encoded = base64.b64encode((ROOT / 'assets/fonts' / file).read_bytes()).decode()
            fonts += f"@font-face{{font-family:'{family}';src:url(data:font/woff2;base64,{encoded}) format('woff2')}}"
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" height="{self.h}" viewBox="0 0 {self.w} {self.h}" role="img" aria-labelledby="title desc"><title id="title">{escape(name)}</title><desc id="desc">{escape(description)}</desc><metadata>Original hypothetical teaching data. QuantCorner / QuantSeras no-image-generator route. Generated by scripts/make_course_figures.py.</metadata><style>{fonts}text{{font-family:Roboto,\'Noto Sans Thai\',sans-serif}}</style>' + ''.join(self.parts) + '</svg>\n'
        suffix = '-mobile' if self.w == 400 else ''
        (ROOT / f'assets/charts/{name}{suffix}.svg').write_text(svg)


mu = np.array([.06, .10, .14])
cov = np.array([[.01, .003, .002], [.003, .0225, .009], [.002, .009, .04]])
def solve(target=None):
    constraints = [{'type':'eq', 'fun':lambda w: w.sum()-1}]
    if target is not None:
        constraints.append({'type':'eq', 'fun':lambda w: w @ mu-target})
    result = minimize(lambda w:w@cov@w, np.ones(3)/3, jac=lambda w:2*cov@w,
                      bounds=[(0,1)]*3, constraints=constraints, method='SLSQP',
                      options={'ftol':1e-13, 'maxiter':1000})
    assert result.success, result.message
    assert abs(result.x.sum()-1)<1e-8
    if target is not None:
        assert abs(result.x@mu-target)<1e-8
    return result.x


def main():
    w_gmv = solve()
    targets = np.linspace(mu.min(), mu.max(), 121)
    weights = np.array([solve(t) for t in targets])
    vols = np.sqrt(np.einsum('ij,jk,ik->i',weights,cov,weights))
    upper_targets = np.linspace(w_gmv@mu, mu.max(), 100)
    upper_weights = np.array([solve(t) for t in upper_targets])
    upper_vols = np.sqrt(np.einsum('ij,jk,ik->i',upper_weights,cov,upper_weights))
    risky = np.array([.08,-.12,.06,-.25,.10,.04])
    wealth = [1000.]
    for r in risky:
        exposure = np.clip(3*(wealth[-1]-800),0,wealth[-1])
        wealth.append(wealth[-1]+exposure*r)
    buyhold = np.r_[1000, 1000*np.cumprod(1+risky)]
    np.testing.assert_allclose(wealth,[1000,1048,958.72,987.2896,846.8224,860.86912,868.1734144])
    yields = np.linspace(.03,.07,101)
    pv = 100000/(1.05**5)
    face_short, face_long = pv/2*1.05**2, pv/2*1.05**8
    liabilities = 100000/(1+yields)**5
    matched = face_short/(1+yields)**2+face_long/(1+yields)**8
    for width in (720,400):
        c = Chart(width,'การผสมสินทรัพย์สองชนิด','ข้อมูลสมมติ · SD ต่อปี A 20%, B 10%',(0,100),(0,22),[0,25,50,75,100],[0,5,10,15,20],'น้ำหนัก A (%)','SD ของพอร์ต (% ต่อปี)')
        w = np.unique(np.r_[np.linspace(0,1,201), 1/3])
        for i,(rho,color,dash) in enumerate([(1,GRAY,'6 5'),(.25,PURPLE,''),(-1,TEAL,'3 3')]):
            sd=np.sqrt(np.maximum(0,(w*.2)**2+((1-w)*.1)**2+2*w*(1-w)*.2*.1*rho))
            c.legend(88+i*23,f'Correlation = {rho:g}',color,dash)
            c.series(w*100,sd*100,color,f'rho-{rho}',dash)
        c.save('course-diversification','Portfolio SD for A 20% and B 10% annual SD, long-only fully invested weights, three hypothetical correlation values. Correlation minus one permits a zero-variance combination at A weight one third.')

        c=Chart(width,'พอร์ตที่สร้างได้และ Efficient frontier','ตัวอย่าง A, B, C · ไม่ขายชอร์ต',(0,22),(4,16),[0,5,10,15,20],[4,6,8,10,12,14,16],'SD ของพอร์ต (% ต่อปี)','ผลตอบแทนคาดหมาย (% ต่อปี)')
        c.legend(90,'ขอบบนที่มีประสิทธิภาพ',PURPLE)
        c.legend(116,'ขอบล่าง (มีพอร์ตอื่นดีกว่า)',GRAY,'6 5')
        for i in range(21):
            for j in range(21-i):
                wg=np.array([i,j,20-i-j])/20
                c.dot(np.sqrt(wg@cov@wg)*100,wg@mu*100,'#bbbbbb',1.5)
        mask=targets < w_gmv@mu
        c.series(vols[mask]*100,targets[mask]*100,GRAY,'lower-boundary','6 5')
        c.series(upper_vols*100,upper_targets*100,PURPLE,'efficient-frontier')
        for i,letter in enumerate('ABC'):
            x,y=np.sqrt(cov[i,i])*100,mu[i]*100
            c.dot(x,y,TEAL,4)
            c.text(c.x(x)+6,c.y(y)-9,letter,17)
        c.dot(np.sqrt(w_gmv@cov@w_gmv)*100,w_gmv@mu*100,PURPLE,5)
        c.text(c.x(np.sqrt(w_gmv@cov@w_gmv)*100)-7,c.y(w_gmv@mu*100)-16,'GMV',15,anchor='end')
        c.save('course-frontier','Three hypothetical assets with annual arithmetic expected returns 6%, 10%, 14% and SD 10%, 15%, 20%. Gray dots are a finite weight grid, not the whole feasible set. Purple curve is the upper minimum-variance boundary beginning at GMV. Covariance inputs and plotted points are in data/course-figures.json.')

        c=Chart(width,'CPPI บนเส้นทางผลตอบแทนเดียวกัน','ข้อมูลสมมติ 6 เดือน · เงินเริ่มต้น 1,000 บาท',(0,6),(600,1200),list(range(7)),[600,800,1000,1200],'เดือน (0 = ก่อนลงทุน)','มูลค่าพอร์ต (บาท)')
        c.legend(88,'CPPI: m = 3, cash return = 0',PURPLE)
        c.legend(111,'ซื้อสินทรัพย์เสี่ยงแล้วถือ',TEAL,'6 5')
        c.legend(134,'Floor คงที่ 800 บาท',GRAY,'3 3')
        c.series(range(7),wealth,PURPLE,'cppi')
        c.series(range(7),buyhold,TEAL,'buy-hold','6 5')
        c.series(range(7),[800]*7,GRAY,'floor','3 3')
        c.save('course-cppi','Six authored monthly returns: 8%, -12%, 6%, -25%, 10%, 4%. CPPI starts at THB1000, fixed floor800, multiplier3, no borrowing, no fees, zero cash return. Lines join monthly observations and do not describe within-month prices. This path does not establish a guarantee against gaps.')

        c=Chart(width,'Duration matching และ Funding ratio','ข้อมูลสมมติ · หนี้ 100,000 บาทในปีที่ 5',(3,7),(.9,1.1),[3,4,5,6,7],[.9,.95,1,1.05,1.1],'Yield ของทุกอายุ (%)','Funding ratio (เท่า)')
        c.legend(88,'ZCB 2 และ 8 ปี: จับคู่ PV + duration',PURPLE)
        c.legend(111,'เงินสดมูลค่าคงที่ ณ เวลาประเมิน',TEAL,'6 5')
        c.legend(134,'สินทรัพย์ = มูลค่าหนี้',GRAY,'3 3')
        c.series(yields*100,matched/liabilities,PURPLE,'matched')
        c.series(yields*100,pv/liabilities,TEAL,'cash','6 5')
        c.series(yields*100,np.ones(len(yields)),GRAY,'fully-funded','3 3')
        c.save('course-duration','At annual-effective flat yield5%, a THB100000 five-year liability has PV78352.6166468. Allocate half of this PV to each two- and eight-year zero-coupon bond. Funding ratios are repriced instantly over parallel flat yields3% to7%. This is a yield sensitivity comparison, not a time path or protection against curve twists.')
    data={'status':'hypothetical','frequency':'Annual expected inputs except six authored monthly CPPI observations',
          'mu':mu.tolist(),'cov':cov.tolist(),'gmv_weights':w_gmv.tolist(),
          'frontier':{'target':targets.tolist(),'sd':vols.tolist(),'weights':weights.tolist()},
          'cppi':{'risky_returns':risky.tolist(),'wealth':wealth,'buyhold':buyhold.tolist(),'floor':800,'multiplier':3},
          'duration':{'yields':yields.tolist(),'liability_pv':liabilities.tolist(),'matched_pv':matched.tolist(),'cash_pv':pv}}
    (ROOT/'data/course-figures.json').write_text(json.dumps(data,indent=2)+'\n')
    print('Generated 8 responsive SVGs from verified hypothetical calculations.')


if __name__=='__main__':
    main()
