"""Computed figures for Advanced Module 2; inputs come from executed lessons."""
import json
from pathlib import Path
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import execute_chapter, course_pages

ROOT = Path(__file__).resolve().parents[1]


def save(chart, name, description):
    chart.save(name, description)
    suffix = '-mobile' if chart.w == 400 else ''
    path = ROOT / f'assets/charts/{name}{suffix}.svg'
    path.write_text(path.read_text().replace('Generated by scripts/make_course_figures.py.',
                                           'Generated by scripts/make_covariance_figures.py.'))


def main():
    page = next(p for p in course_pages('advanced', 2) if p['file'] == 'time-varying-risk')
    _, ns, _ = execute_chapter(page)
    days = np.arange(5, 19)
    rolling = np.sqrt(ns['rolling_after'].to_numpy()[4:]) * 100
    ewma = np.sqrt(ns['ewma_h'][5:]) * 100
    horizon = np.arange(1, 61)
    forecast_garch = np.sqrt(ns['garch_forecast_path']) * 100
    forecast_ewma = np.sqrt(ns['ewma_forecast_path']) * 100
    long_run = np.full(60, np.sqrt(ns['long_run_variance']) * 100)
    for width in (720, 400):
        chart = Chart(width, 'เมื่อ shock หลุดจากหน้าต่าง', 'ข้อมูลสมมติ · shock 5% ในวันที่ 6',
                      (5, 18), (0.8, 2.6), [5, 10, 15, 18], [1, 1.5, 2, 2.5],
                      'วันล่าสุดที่สังเกตแล้ว', 'SD พยากรณ์วันถัดไป (%)')
        chart.legend(96, 'Rolling 5 วัน', PURPLE)
        chart.legend(124, 'EWMA: λ = 0.90', TEAL, '6 5')
        chart.series(days, rolling, PURPLE, 'rolling-next-day-sd')
        chart.series(days, ewma, TEAL, 'ewma-next-day-sd', '6 5')
        save(chart, 'advanced-risk-window', 'Original hypothetical residuals: magnitude 1% except a positive 5% shock on day 6. Each x is the last observed day; y is the next-day standard deviation forecast. Rolling uses the five most recent squared residuals. EWMA starts at variance 0.0001 and uses lambda 0.90. Lines join daily values; no forecast uses future observations.')

        chart = Chart(width, 'คาดความเสี่ยงจากวันเดียวกัน', 'หลังเห็นวันที่ 6 · พารามิเตอร์สมมติ',
                      (1, 60), (0.8, 2), [1, 20, 40, 60], [1, 1.5, 2],
                      'ระยะพยากรณ์ (วัน)', 'รากของ variance ที่คาด (%)')
        chart.legend(88, 'GARCH: α + β = 0.98', PURPLE)
        chart.legend(112, 'EWMA: ค่าคาดหมายคงที่', TEAL, '6 5')
        chart.legend(136, 'SD ระยะยาวของ GARCH', GRAY, '3 3')
        chart.series(horizon, forecast_garch, PURPLE, 'garch-forecast-sd')
        chart.series(horizon, forecast_ewma, TEAL, 'ewma-forecast-sd', '6 5')
        chart.series(horizon, long_run, GRAY, 'garch-long-run-sd', '3 3')
        save(chart, 'advanced-risk-forecast', 'Original fixed-origin variance forecasts after day 6. GARCH(1,1): omega=0.000002, alpha=0.08, beta=0.90, next variance=0.000292, long-run variance=0.0001. EWMA next variance=0.00034; expected future variance stays at that level under its model, not an imposed zero-shock path. Plotted square roots of expected variances are not expectations of future standard deviations.')
    data = {
        'status': 'Original hypothetical teaching fixtures; no market-data fit',
        'window': {'observed_day': days.tolist(), 'rolling_next_day_sd_percent': rolling.tolist(),
                   'ewma_next_day_sd_percent': ewma.tolist()},
        'forecast': {'horizon': horizon.tolist(), 'garch_sd_percent': forecast_garch.tolist(),
                     'ewma_sd_percent': forecast_ewma.tolist(), 'long_run_sd_percent': long_run.tolist()},
    }
    (ROOT / 'data/advanced-covariance-figures.json').write_text(json.dumps(data, indent=2) + '\n')
    print('Generated 4 Advanced Module 2 responsive SVGs')


if __name__ == '__main__':
    main()
