"""Computed teaching figures for Advanced expected returns and views."""
import json
from pathlib import Path
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import course_pages, execute_chapter

ROOT = Path(__file__).resolve().parents[1]


def save(chart, name, description):
    chart.save(name, description)
    suffix = '-mobile' if chart.w == 400 else ''
    path = ROOT / f'assets/charts/{name}{suffix}.svg'
    path.write_text(path.read_text().replace('Generated by scripts/make_course_figures.py.',
                                           'Generated by scripts/make_expected_return_figures.py.'))


def main():
    pages = {p['file']:p for p in course_pages('advanced',3)}
    _, estimation, _ = execute_chapter(pages['expected-return-estimation'])
    _, bl, _ = execute_chapter(pages['black-litterman'])
    years = np.linspace(1,20,153)
    se = 100*estimation['annual_sigma']/np.sqrt(years)
    error_sd = np.sort(np.unique(np.r_[np.linspace(0,.08,81),np.sqrt(bl['omega'][0,0])]))
    posterior_c = np.array([bl['bl_posterior'](
        bl['covariance'],bl['pi'],bl['P'][:1],bl['Q'][:1],np.array([[sd**2]]),bl['tau'])[0][2]
        for sd in error_sd])*100
    prior_c = np.full(len(error_sd),100*bl['pi'][2])
    view_c = np.full(len(error_sd),100*bl['Q'][0])
    for width in (720,400):
        chart = Chart(width,'ความไม่แน่นอนของค่าเฉลี่ย','แบบจำลองสมมติ · SD รายปี 20%',
                      (1,20),(0,21),[1,5,10,15,20],[0,5,10,15,20],
                      'ประวัติข้อมูล (ปี)','Standard Error (จุดเปอร์เซ็นต์)')
        chart.legend(96,'SE ของค่าเฉลี่ยรายปี',PURPLE)
        chart.series(years,se,PURPLE,'annual-mean-standard-error')
        save(chart,'advanced-mean-uncertainty','Theoretical standard error of an annual arithmetic mean under the additive IID constant-parameter model with annual volatility 20%. SE = 0.20/sqrt(years). This curve is not portfolio volatility, a prediction interval, or an empirical guarantee that older data remain relevant.')
        chart = Chart(width,'เชื่อ View มากแค่ไหน','สินทรัพย์ C · ใช้ View เดียว',
                      (0,8),(1.5,3),[0,2,4,6,8],[1.5,2,2.5,3],
                      'SD ของ View error (%)','Expected excess return (%/ปี)')
        chart.legend(88,'Posterior ของ C',PURPLE)
        chart.legend(112,'Prior ของ C',TEAL,'6 5')
        chart.legend(136,'View: C ให้ 2.5%/ปี',GRAY,'3 3')
        chart.series(error_sd*100,posterior_c,PURPLE,'single-view-posterior-c')
        chart.series(error_sd*100,prior_c,TEAL,'prior-c','6 5')
        chart.series(error_sd*100,view_c,GRAY,'view-c','3 3')
        save(chart,'advanced-view-confidence','Original three-asset teaching fixture. This controlled comparison retains only the absolute view on C, Q=0.025, prior mean C=0.018375 and prior variance of mean C=0.0005. The x-axis varies view-error SD, not probability. At zero error variance the view is exact; growing uncertainty draws the posterior toward the prior. The second relative view in the main lesson is deliberately omitted to isolate this effect.')
    (ROOT/'data/advanced-expected-return-figures.json').write_text(json.dumps({
        'status':'Original hypothetical model illustrations',
        'mean':{'years':years.tolist(),'annual_sigma':float(estimation['annual_sigma']),
                'annual_mean_standard_error_pp':se.tolist()},
        'view':{'view_error_sd_percent':(error_sd*100).tolist(),'posterior_c_percent':posterior_c.tolist(),
                'prior_c_percent':prior_c.tolist(),'view_c_percent':view_c.tolist()}
    },indent=2)+'\n')
    print('Generated 4 Advanced Module 3 responsive SVGs')


if __name__ == '__main__':
    main()
