"""Original PCA risk-share and partial-correlation figures; no market data."""
from pathlib import Path
import json
import numpy as np
from make_course_figures import Chart, PURPLE, TEAL, GRAY
from make_course_notebooks import execute_chapter

ROOT = Path(__file__).resolve().parents[1]


def save(chart, name, description):
    chart.save(name, description)
    suffix = '-mobile' if chart.w == 400 else ''
    path = ROOT / f'assets/charts/{name}{suffix}.svg'
    path.write_text(path.read_text().replace(
        'Generated by scripts/make_course_figures.py.',
        'Generated by scripts/make_ml_diversification_figures.py.'))


def main():
    _, pca, _ = execute_chapter({'file': 'pca-diversification'})
    _, network, _ = execute_chapter({'file': 'asset-networks'})
    data_share = 100 * pca['explained_ratio']
    risk_share = 100 * pca['risk_shares']
    partial = network['partial']
    for width in (720, 400):
        chart = Chart(width, 'ข้อมูลกับความเสี่ยงพอร์ต', 'ข้อมูลจำลอง · ฝึก 208 สัปดาห์ · EW หกตัว',
                      (.5, 6.5), (0, 60), [], [0, 20, 40, 60], 'Principal component', 'ส่วนแบ่ง (%)')
        chart.legend(94, 'ความแปรปรวนของข้อมูล', PURPLE)
        chart.legend(124, 'ความแปรปรวนของพอร์ต EW', TEAL)
        bw = 17 if width == 400 else 30
        for k in range(6):
            chart.text(chart.x(k + 1), chart.bottom + 25, f'PC{k + 1}', 13 if width == 400 else 16, anchor='middle')
            for offset, value, color, series in [(-bw, data_share[k], PURPLE, 'data-variance'),
                                                 (1, risk_share[k], TEAL, 'portfolio-variance')]:
                chart.parts.append(f'<rect data-series="{series}" data-pc="{k+1}" data-value="{value:.12g}" x="{chart.x(k+1)+offset:.4f}" y="{chart.y(value):.4f}" width="{bw-2}" height="{chart.bottom-chart.y(value):.4f}" fill="{color}"/>')
        save(chart, 'ml-pca-risk-shares', 'Original six-asset Gaussian weekly simulation, seed 317; 208 training weeks. Purple bars are covariance-PCA explained variance ratios. Teal bars are equal-weight portfolio variance contributions lambda_k*(v_k.T*w)^2 divided by portfolio variance. Both sum to 100 percent but answer different questions. The first two PCs explain about 61.47 percent of data variance and about 92.04 percent of this portfolio variance. No market observations or performance guarantee.')

        # A matrix chart preserves every pair and signed value without a distorted 2D network layout.
        chart = Chart(width, '', '', (0, 1), (0, 1), [], [], '', '')
        chart.parts = [f'<rect width="{width}" height="{chart.h}" fill="#fff"/>']
        chart.text(20, 32, 'ความสัมพันธ์หลังควบคุมตัวอื่น', 19 if width == 400 else 26)
        chart.text(20, 62, f'Partial correlation · alpha = {network["chosen_alpha"]:.2f}', 15 if width == 400 else 18, color=GRAY)
        chart.text(20, 90, 'ข้อมูลจำลอง 208 สัปดาห์ · ค่าประมาณ', 14 if width == 400 else 17, color=GRAY)
        cell = 46 if width == 400 else 51
        left, top = (width - 6 * cell) / 2 + 10, 143
        for i, asset in enumerate(network['assets']):
            chart.text(left + cell * (i + .5), top - 13, asset, 16, anchor='middle')
            chart.text(left - 13, top + cell * (i + .5) + 5, asset, 16, anchor='middle')
            for j in range(6):
                value = float(partial[i, j])
                if i == j:
                    fill, label = '#eeeeee', '1'
                else:
                    color = np.array([98, 0, 238]) if value >= 0 else np.array([0, 121, 110])
                    strength = min(abs(value), 1) * .60
                    rgb = np.rint(255 * (1 - strength) + color * strength).astype(int)
                    fill = '#' + ''.join(f'{c:02x}' for c in rgb)
                    label = '0' if abs(value) < 1e-8 else f'{value:.2f}'
                chart.parts.append(f'<rect data-row="{network["assets"][i]}" data-column="{network["assets"][j]}" data-value="{value:.12g}" x="{left+j*cell:.3f}" y="{top+i*cell:.3f}" width="{cell}" height="{cell}" fill="{fill}" stroke="#ddd"/>')
                chart.text(left + (j + .5) * cell, top + (i + .5) * cell + 5, label, 13 if width == 400 else 16, anchor='middle')
        chart.text(20, chart.h - 67, 'สีม่วง: บวก · สีเขียว: ลบ · อ่านเครื่องหมายร่วมด้วย', 12 if width == 400 else 16)
        chart.text(20, chart.h - 40, 'ศูนย์ในค่าประมาณไม่ได้ยืนยันว่าไม่มีความสัมพันธ์', 12 if width == 400 else 16, color=GRAY)
        save(chart, 'ml-partial-correlation', 'Original six-asset Gaussian simulation, seed 317; 208 training weeks. Graphical Lasso alpha 0.02 selected from 0.02, 0.08, 0.20, 0.60 by four chronological validation folds with fold-specific standardization. Each cell is -K_ij/sqrt(K_ii*K_jj), with diagonal one. Values are estimated partial correlations, not causal effects. Purple indicates positive and teal negative; signed numeric labels also encode meaning. Zero estimates do not establish population independence. The selected estimate has 11 edges, while the known simulated population has five.')
    values = {'data_status': 'Original hypothetical Gaussian simulation',
              'seed': 317, 'train_weeks': 208,
              'pca': {'data_variance_percent': data_share.tolist(), 'portfolio_variance_percent': risk_share.tolist()},
              'network': {'assets': network['assets'].tolist(), 'alpha': network['chosen_alpha'], 'partial_correlation': partial.tolist()}}
    (ROOT / 'data/ml-diversification-figures.json').write_text(json.dumps(values, indent=2) + '\n')
    print('Generated four responsive ML diversification SVGs and numerical data')


if __name__ == '__main__':
    main()
