import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {simulate, calculateAllocation, protectivePut, SCENARIOS, toCSV} from './math.mjs';
import CountUp from './components/CountUp.jsx';
import Stepper from './components/Stepper.jsx';
import AnimatedList from './components/AnimatedList.jsx';
import BlurText from './components/BlurText.jsx';
import './components/components.css';

const N = (v,d=2) => Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const scenarioNames={rally:'Rally',crash:'Crash',whipsaw:'Whipsaw',recovery:'Recovery'};
const lineSeries=[{key:'cppi',label:'CPPI',className:'line-cppi'}, {key:'buyHold',label:'Buy & hold',className:'line-benchmark',dash:'7 5'}, {key:'constantMix',label:'Constant mix 60/40',className:'line-mix',dash:'2 4'}, {key:'floor',label:'Floor',className:'line-floor',dash:'6 5'}];

function Chart({rows,compact=false,series=lineSeries,xKey='month',xLabel='Month',unit='Portfolio value · units'}) {
  const container=useRef(null),[width,setWidth]=useState(520),[hover,setHover]=useState(null);
  useEffect(()=>{const observer=new ResizeObserver(entries=>setWidth(Math.max(260,entries[0].contentRect.width)));observer.observe(container.current);return()=>observer.disconnect();},[]);
  const height=compact?244:290,pad={left:47,right:16,top:25,bottom:43};
  const values=rows.flatMap(r=>series.map(s=>r[s.key]));
  const minimum=Math.floor((Math.min(...values)-5)/10)*10,maximum=Math.ceil((Math.max(...values)+5)/10)*10;
  const x=i=>pad.left+i/(rows.length-1)*(width-pad.left-pad.right),y=v=>pad.top+(maximum-v)/(maximum-minimum)*(height-pad.top-pad.bottom);
  const active=hover!==null?rows[hover]:null;
  return <div className="chart-shell" ref={container}>
    <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${unit}. ${series.map(s=>s.label).join(', ')}. Data table below.`} onMouseMove={e=>{const rect=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(rows.length-1,Math.round((e.clientX-rect.left-pad.left)/(width-pad.left-pad.right)*(rows.length-1)))));}} onMouseLeave={()=>setHover(null)}>
      <text x={pad.left} y={13} className="chart-unit">{unit}</text>
      {[0,1,2,3,4].map(i=>{const v=minimum+(maximum-minimum)*i/4;return <g key={i}><line className="gridline" x1={pad.left} x2={width-pad.right} y1={y(v)} y2={y(v)}/><text className="axis" x={pad.left-10} y={y(v)+4} textAnchor="end">{N(v,v%1?1:0)}</text></g>;})}
      {[0,Math.round((rows.length-1)/3),Math.round(2*(rows.length-1)/3),rows.length-1].map(i=><text key={i} className="axis" x={x(i)} y={height-22} textAnchor="middle">{rows[i][xKey]}</text>)}
      <text className="axis" x={width-pad.right} y={height-3} textAnchor="end">{xLabel}</text>
      {series.map(s=><path key={s.key} className={s.className} d={rows.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r[s.key])}`).join(' ')} fill="none" strokeWidth={s.key==='cppi'||s.key==='wealth'?2.8:1.8} strokeDasharray={s.dash}/>) }
      {active&&<g><line className="crosshair" x1={x(hover)} x2={x(hover)} y1={pad.top} y2={height-pad.bottom}/>{series.map(s=><circle key={s.key} className={s.className} cx={x(hover)} cy={y(active[s.key])} r="3"/>)}</g>}
    </svg>
    <div className="chart-legend">{series.map(s=><span key={s.key}><i className={s.className} style={{borderTopStyle:s.dash?'dashed':'solid'}}/>{s.label}</span>)}</div>
    {!compact&&<p className="chart-readout small muted">{active?`${xLabel} ${active[xKey]} · ${series.map(s=>`${s.label} ${N(active[s.key])}`).join(' / ')}`:'Move over the chart to inspect values · ดูข้อมูลทุกจุดได้ในตารางด้านล่าง'}</p>}
  </div>;
}

function HomeDemo(){const [scenario,setScenario]=useState('recovery'),result=useMemo(()=>simulate({scenario}),[scenario]);return <div className="hero-demo">
  <div className="demo-top"><span className="eyebrow">A SMALL EXPERIMENT</span><span className="synthetic-label">ILLUSTRATIVE</span></div>
  <h2>One market. <br/>Different outcomes.</h2><p className="small muted">เงินเริ่มต้น 100 · Floor 90% · Multiplier 3</p>
  <div className="scenario-mini" aria-label="Illustrative market scenario">{['recovery','rally','crash'].map(id=><button key={id} aria-pressed={scenario===id} onClick={()=>setScenario(id)}>{scenarioNames[id]}</button>)}</div>
  <Chart rows={result.rows} compact/>
  <div className="demo-bottom"><div><span className="small muted">CPPI · END OF YEAR</span><strong><CountUp to={result.metrics.final}/> <span className="small muted">units</span></strong></div><a className="text-link" href="lab.html">Try the full lab ↗</a></div>
  <p className="small muted demo-note">12 เดือนสมมติ · ดอกเบี้ยและต้นทุน 0% · ไม่กู้ยืม<br/>CPPI Floor เป็นเป้าหมาย ไม่มีการรับประกัน</p>
  <details className="compact-data"><summary>View example data</summary><DataTable rows={result.rows}/></details>
  </div>;}

function Range({id,label,value,onChange,min,max,step=1,suffix=''}){return <div className="range-control"><label htmlFor={id}>{label}<output htmlFor={id}>{N(value,step<1?1:0)}{suffix}</output></label><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/><div className="range-bounds"><span>{min}{suffix}</span><span>{max}{suffix}</span></div></div>;}
function DataTable({rows}){return <div className="table-scroll" tabIndex="0" role="region" aria-label="Monthly simulation data"><table><caption>Monthly observations · all portfolio values in units</caption><thead><tr><th scope="col">Month</th><th scope="col">CPPI</th><th scope="col">Buy & hold</th><th scope="col">Mix 60/40</th><th scope="col">Floor</th><th scope="col">Risky target</th></tr></thead><tbody>{rows.map(r=><tr key={r.month}><th scope="row">{r.month}</th><td>{N(r.cppi)}</td><td>{N(r.buyHold)}</td><td>{N(r.constantMix)}</td><td>{N(r.floor)}</td><td>{N(r.exposure)}</td></tr>)}</tbody></table></div>;}

function CppiLab(){
  const [scenario,setScenario]=useState('crash'),[floorPct,setFloor]=useState(90),[multiplier,setMultiplier]=useState(3),[runs,setRuns]=useState([]),[message,setMessage]=useState('');
  const result=useMemo(()=>simulate({floorPct,multiplier,scenario}),[floorPct,multiplier,scenario]);
  const m=result.metrics, allocation=calculateAllocation({floorPct,multiplier});
  const save=()=>{const item={id:Date.now()+'-'+runs.length,label:`${scenarioNames[scenario]} · Floor ${floorPct}% · m ${multiplier} · End ${N(m.final)}`,scenario,floorPct,multiplier};setRuns(old=>[item,...old].slice(0,6));setMessage('บันทึกชุดทดลองแล้ว เก็บในหน้านี้ได้สูงสุด 6 ชุด');};
  const restore=run=>{setScenario(run.scenario);setFloor(run.floorPct);setMultiplier(run.multiplier);setMessage('เรียกคืนสมมติฐานชุดที่บันทึกแล้ว');};
  const download=()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+toCSV(result)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`cppi-${scenario}-floor-${floorPct}-m-${multiplier}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('ดาวน์โหลด CSV พร้อมพารามิเตอร์และผลรายเดือนแล้ว');};
  return <div className="lab-card"><div className="lab-layout"><div className="lab-controls"><p className="eyebrow">YOUR ASSUMPTIONS</p><label htmlFor="scenario">Market path</label><select id="scenario" value={scenario} onChange={e=>setScenario(e.target.value)}>{SCENARIOS.map(s=><option key={s.id} value={s.id}>{scenarioNames[s.id]} · {s.label}</option>)}</select><p className="small muted">{SCENARIOS.find(s=>s.id===scenario).description}</p><Range id="floor-control" label="Terminal floor" value={floorPct} onChange={setFloor} min={70} max={100} suffix="%"/><Range id="multiplier-control" label="Multiplier" value={multiplier} onChange={setMultiplier} min={1} max={6} step={0.5} suffix="×"/><div className="allocation-snapshot"><span className="small muted">INITIAL RISKY ALLOCATION</span><strong><CountUp to={allocation.weight*100} digits={1}/>%</strong><div className="allocation-bar" role="img" aria-label={`Risky ${N(allocation.weight*100,1)}%, safe ${N((1-allocation.weight)*100,1)}%`}><span style={{width:`${allocation.weight*100}%`}}/></div><span className="small muted">Remaining {N((1-allocation.weight)*100,1)}% in safe asset</span></div><button className="button" onClick={()=>{setFloor(90);setMultiplier(3);setScenario('crash');setMessage('คืนค่าเริ่มต้นแล้ว');}}>Reset assumptions</button></div>
  <div className="lab-results"><div className="result-top"><div><p className="eyebrow">SIMULATED PORTFOLIO PATHS</p><h3>{scenarioNames[scenario]} scenario</h3></div><span className="pill">12 months</span></div><div className="metrics-row"><div><span>CPPI final value</span><strong><CountUp to={m.final}/></strong><small>units · initial 100</small></div><div><span>Total return</span><strong>{m.returnPct>0?'+':''}<CountUp to={m.returnPct}/>%</strong><small>over this 1-year path</small></div><div><span>Max drawdown</span><strong><CountUp to={m.maxDrawdownPct}/>%</strong><small>monthly observations</small></div></div><Chart rows={result.rows}/>
  <div className={`result-insight ${m.floorBreached?'breached':''}`} role="status"><strong>{m.floorBreached?'Floor breached':m.locked?'Cash locked':'Floor held in this path'}</strong><p>{m.floorBreached?'มูลค่าพอร์ตต่ำกว่า Floor ในเส้นทางนี้ การปรับพอร์ตเป็นช่วงเวลาไม่สามารถปิดความเสี่ยงจากราคาที่กระโดดลงได้ เมื่อ Cushion หมด เงินลงทุนเสี่ยงเป็นศูนย์ จึงไม่ได้รับการฟื้นตัวของตลาด':m.locked?'Cushion เป็นศูนย์ พอร์ตจึงถือสินทรัพย์ปลอดความเสี่ยงทั้งหมดและไม่ได้รับการฟื้นตัวของสินทรัพย์เสี่ยง':'จุดสังเกตรายเดือนของเส้นทางนี้ยังไม่ต่ำกว่า Floor ผลนี้ไม่ได้รับรองว่าจะป้องกันได้ในเส้นทางอื่นหรือระหว่างเดือน'}</p></div>
  <div className="lab-actions"><button className="button primary" onClick={save}>Save this run</button><button className="button" onClick={download}>Download CSV</button></div><p className="small muted" role="status">{message||'Saved runs stay in this page until refresh.'}</p></div></div>
  <details className="data-details"><summary>View monthly data & benchmark results</summary><div className="benchmark-summary">Buy & hold: {N(result.benchmarkMetrics.buyHold.final)} units · Constant mix: {N(result.benchmarkMetrics.constantMix.final)} units</div><DataTable rows={result.rows}/><p className="small muted">Risky target คือเงินลงทุนเสี่ยงหลังปรับพอร์ต ณ จุดนั้น ค่าเดือน 12 แสดงเพื่ออธิบายสูตร ไม่มีการซื้อขายที่วันสิ้นงวด</p></details>
  <section className="saved-runs"><h3>Saved experiments <span className="small muted">{runs.length}/6</span></h3>{runs.length?<AnimatedList items={runs} onItemSelect={restore}/>:<p className="small muted">บันทึกชุดทดลอง แล้วเลือกกลับมาเทียบสมมติฐานได้</p>}</section></div>;
}

function AllocationGuide(){return <Stepper><div><p className="eyebrow">01 / SET THE FLOOR</p><h3>เริ่มจากส่วนที่ต้องการปกป้อง</h3><p>มูลค่าพอร์ต 100 หน่วย และตั้ง Floor 90 หน่วย ณ สิ้นปี ในตัวอย่างนี้ดอกเบี้ย 0% จึงใช้ Floor 90 ได้ทุกเดือน</p><div className="worked-equation">V = 100 &nbsp; F = 90</div></div><div><p className="eyebrow">02 / FIND THE CUSHION</p><h3>เงินส่วนเกินเหนือ Floor</h3><p>Cushion คือส่วนต่างระหว่างมูลค่าพอร์ตกับ Floor ยังไม่ใช่จำนวนเงินลงทุนในสินทรัพย์เสี่ยง</p><div className="worked-equation">C = 100 − 90 = 10</div></div><div><p className="eyebrow">03 / ALLOCATE & REBALANCE</p><h3>คูณ Cushion ด้วย Multiplier</h3><p>เมื่อ m = 3 ลงทุนเสี่ยง 30 หน่วย และถือสินทรัพย์ปลอดความเสี่ยง 70 หน่วย หลังราคาขยับต้องคำนวณใหม่ หากสินทรัพย์เสี่ยงลด 40% ก่อนปรับ พอร์ตจะเหลือ 88 หน่วย ต่ำกว่า Floor 90</p><div className="worked-equation">E = 3 × 10 = 30<br/>30 × 0.6 + 70 = 88</div></div></Stepper>;}

function PutLab(){const [strike,setStrike]=useState(90),[premium,setPremium]=useState(4),[terminal,setTerminal]=useState(80);const r=protectivePut({strike,premium,terminal});const rows=Array.from({length:21},(_,i)=>{const t=i*10,v=protectivePut({strike,premium,terminal:t});return {price:t,wealth:v.terminalWealth,cost:v.initialCost,stock:t};});return <div className="lab-card put-card"><div className="lab-layout"><div className="lab-controls"><p className="eyebrow">ONE ASSET + ONE PUT</p><p className="small muted">Spot today = 100 units<br/>European put · held to expiry</p><Range id="put-strike" label="Strike" value={strike} onChange={v=>{setStrike(v);setPremium(p=>Math.max(p,v-100,0));}} min={70} max={120}/><Range id="put-premium" label="Premium paid" value={premium} onChange={setPremium} min={Math.max(0,strike-100)} max={40} step={0.5}/><Range id="put-terminal" label="Asset at expiry" value={terminal} onChange={setTerminal} min={0} max={200}/></div><div className="lab-results"><div className="result-top"><div><p className="eyebrow">PAYOFF IS NOT PROFIT</p><h3>What remains at expiry?</h3></div></div><div className="metrics-row"><div><span>Put payoff</span><strong><CountUp to={r.putPayoff}/></strong><small>units</small></div><div><span>Terminal wealth</span><strong><CountUp to={r.terminalWealth}/></strong><small>asset + put</small></div><div><span>Net profit / loss</span><strong><CountUp to={r.profit}/></strong><small>initial cost {N(r.initialCost)}</small></div></div><Chart rows={rows} xKey="price" xLabel="Asset price at expiry" unit="Terminal wealth / initial cost · units" series={[{key:'wealth',label:'Asset + put',className:'line-cppi'},{key:'stock',label:'Asset only',className:'line-benchmark',dash:'7 5'},{key:'cost',label:'Initial cost',className:'line-floor',dash:'6 5'}]}/><div className="result-insight"><strong>Wealth {N(r.terminalWealth)} − cost {N(r.initialCost)} = {N(r.profit)} units</strong><p>ที่ราคาเมื่อหมดอายุ {N(terminal)} หน่วย Put จ่าย {N(r.putPayoff)} หน่วย ผลตอบแทนจากต้นทุนรวมเท่ากับ {N(r.returnPct)}% กราฟแสดงผลลัพธ์สำหรับราคาปลายทางหลายค่า ไม่ใช่เส้นทางราคาตามเวลา</p></div><details className="data-details"><summary>View terminal payoff table</summary><div className="table-scroll" tabIndex="0" role="region" aria-label="Protective put payoff table"><table><thead><tr><th>Asset at expiry</th><th>Asset + put</th><th>Initial cost</th><th>Profit / loss</th></tr></thead><tbody>{rows.map(row=><tr key={row.price}><td>{row.price}</td><td>{N(row.wealth)}</td><td>{N(row.cost)}</td><td>{N(row.wealth-row.cost)}</td></tr>)}</tbody></table></div></details></div></div></div>;}

const mounts={'home-demo':<HomeDemo/>,'hero-headline':<BlurText text="Design the protection."/>,'cppi-lab':<CppiLab/>,'allocation-guide':<AllocationGuide/>,'put-lab':<PutLab/>};
for(const [id,element] of Object.entries(mounts)){const node=document.getElementById(id);if(node)createRoot(node).render(element);}
